(use-modules (opencog ure))

(add-to-load-path "/home/noskill/projects/pln/opencog/pln/rules/propositional/")
(load-from-path "modus-ponens.scm")
(load-from-path "contraposition.scm")

(define (make-rb rule_base)
    (MemberLink (DefinedSchemaNode "modus-ponens-inheritance-rule") rule_base)
    (MemberLink (DefinedSchemaNode "modus-ponens-implication-rule") rule_base)
    (MemberLink (DefinedSchemaNode "modus-ponens-subset-rule")  rule_base)
    (MemberLink (DefinedSchemaNode "contraposition-implication-rule") rule_base)
    (MemberLink (DefinedSchemaNode "contraposition-inheritance-rule") rule_base)
)

(cog-set-tv! (ConceptNode "apple") (stv 0.8 0.9))
(InheritanceLink (stv 0.8 0.4)
		 (ConceptNode "apple")
                 (ConceptNode "fruit"))
(define rbs (ConceptNode "pln"))
(define target (ConceptNode "fruit"))
(make-rb rbs)
;(cog-bc rbs target)
